[server]
# server_id = 1
channel_id = [1, 2]
privilege_group_id = 5
# redis_server = ""

# [[permissions]]
# channel_id = 1
# it means set i_channel_needed_permission_modify_power to 75 and i_channel_needed_delete_power to 60
# See: https://gist.github.com/EdisonJwa/630383a12281f3db2186a14e1d0fa901 for more key information
# map = [[86, 75], [133, 60]]

[misc]
# interval = 5

# [custom_message]
# channel_not_found = "I can't find you channel."
# create_channel = "Your Channel has been created!"
# move_to_channel = "You have been moved into your channel."

# [raw_query]
# This section priority is higher than web_query
# server = ""
# port = 10011
# user = "serveradmin"
# password = "114514"

[web_query]
# This method may significantly increase CPU usage.
server = "https://localhost:10080"
api_key = "BAA114514"